apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ek8vuu0eo-dotnet-basic 
  janus-idp.io/tekton: ek8vuu0eo-dotnet-basic
  backstage.io/kubernetes-id: ek8vuu0eo-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ek8vuu0eo-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml